<?php
/**
 * SMTP Configuration (auto-generated by installer)
 * Only Website SMTP (support@) is stored here.
 * Admin Email SMTP (info@ Zoho) is configured in Admin Panel → Settings.
 */

// Website SMTP - support@softandpix.com (cPanel hosting)
// Used for: ALL automatic system emails
$smtp_config = [
    'support' => [
        'host'       => 'mail.softandpix.com',
        'port'       => 465,
        'username'   => 'support@softandpix.com',
        'password'   => '',
        'encryption' => 'ssl',
        'from_name'  => 'SoftandPix Support',
        'from_email' => 'support@softandpix.com',
    ],
];
